# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# Dependabot configuration file to keep dependencies updated
version: 2
updates:
  # Ruby (Bundler) dependencies
  - package-ecosystem: "bundler"
    directory: "/"  # Location of the Gemfile
    schedule:
      interval: "weekly"  # Adjusted to weekly to reduce frequency
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "rails"  # Example of ignored dependency; adjust as needed
