# Dependabot configuration file for a Jekyll site hosted on GitHub Pages
version: 2
updates:
  # Ruby (Bundler) dependencies for Jekyll
  - package-ecosystem: "bundler"
    directory: "/"  # Location of the Gemfile
    schedule:
      interval: "weekly"  # Regular updates to stay current with Jekyll and plugins
      day: "monday"       # Choose a low-traffic day for updates
      time: "04:00"       # Schedule at a low-traffic time (UTC)
    open-pull-requests-limit: 5  # Limit to manage PR volume
    labels:
      - "dependencies"
      - "jekyll"
    commit-message:
      prefix: "deps:"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"  # Location of GitHub Actions workflows
    schedule:
      interval: "daily"  # Frequent updates for CI/CD pipeline security
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3
    labels:
      - "ci"
      - "dependencies"
    commit-message:
      prefix: "ci-deps:"
