# If this file changes, restart server process.
# Site settings
# access via {{ site.title }}, {{ site.email }}, {{ site.myvariable }}, etc.

title: An exercise in futility
markdown: kramdown
email: raystanza@js3tech.com
description: >- # ignore newlines until "baseurl:"
  My goal is showcasing acts of futility.
baseurl: "" # e.g. /docs
url: "https://raystanza.uk"
twitter_username: realcaptgeech
github_username:  raystanza

author:
  name: Jim Sines
  email: raystanza@js3tech.com

# Build settings

plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-github-metadata
  - jemoji
  - kramdown

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - "sitemap.xml"
  - "feed.xml"
  - "LICENSE"
  - "README.md"
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/

github: [metadata]
