# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
# YAML references:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# access via {{ site.title }}, {{ site.email }}, {{ site.myvariable }}, etc.

title: Ray's Jekyll Site
email: raystanza@js3tech.com
description: >- # ignore newlines until "baseurl:"
  This is a test of fun things that one can do with Jekyll 
  and GitHub Pages...Nothing more, nothing less.
baseurl: "" # e.g. /docs
url: "https://raystanza.github.io" 
twitter_username: chundersnatch
github_username:  raystanza
show_downloads: true

# Build settings
#remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-github-metadata
#  - jekyll-theme-midnight
  - jemoji
  - kramdown
#  - jekyll-remote-theme

github: [metadata]
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
