# Site settings
title: An exercise in futility
markdown: kramdown
email: raystanza@raystanza.uk
description: >- # ignore newlines until "baseurl:"
  This is a playground where an alternate 'Me' lives.
baseurl: "" # e.g. /docs
url: "https://raystanza.uk"
twitter_username: realcaptgeech
github_username: raystanza

author: _data/author.yml

# Default Open Graph Settings
og:
  title: "An Exercise in Futility"
  description: "A personal blog and portfolio by Jim Sines."
  type: "website"
  image: "/assets/icons/og-image-original.png"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-github-metadata
  - jemoji
  - jekyll-seo-tag

collections_dir: all_collections
collections:
  posts:
    output: true
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
  - scope:
      path: "_projects"
    values:
      layout: "project"
      permalink: /projects/:title/

seo:
  title: "An Exercise in Futility"
  description: "A personal blog and portfolio by Jim Sines."
  url: "https://raystanza.uk"
  image: "/assets/icons/og-image.png"
  twitter: "@realcaptgeech"

# Excluded items
exclude:
  - "sitemap.xml"
  - "feed.xml"
  - "LICENSE"
  - "README.md"
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/

github: [metadata]
