# Site settings
title: An exercise in futility
markdown: kramdown
email: raystanza@raystanza.uk
description: >- # ignore newlines until "baseurl:"
  This is a playground where an alternate 'Me' lives.
baseurl: "" # e.g. /docs
url: "https://raystanza.uk"
twitter_username: realcaptgeech
github_username: raystanza

author:
  name: Jim Sines
  email: raystanza@raystanza.uk
  dp: https://avatars.githubusercontent.com/u/51805268?v=4
  tagline: "<p>Coded by Jim Sines</p>"
  location: "USA"
  profession: "Wheelchair Repair Technician"
  education:
  - name: ITT Tech
    description: Technical College
    duration: 1 year
  languages:
  - name: HTML
    description: "Markup language for structuring web content"
  - name: CSS
    description: "Stylesheet language for designing web pages"
  - name: JavaScript
    description: "Dynamic scripting language for web applications"
  - name: PHP
    description: "Server-side scripting language for web development"
  stacks:
  - name: LAMP Stack
    description: "Linux, Apache, MySQL, PHP"
  - name: LIVT Stack
    description: "Laravel, Inertia.js, Vue.js, Tailwind CSS"
  backend:
  - name: Apache
    description: "Web server software"
  - name: MySQL Server
    description: "Relational database management system"
  - name: Laravel
    description: "PHP framework for building web applications"
  - name: Linode VPS
    description: "Virtual private servers for hosting and deployment"
  frontend:
  - name: Vue
    description: "JavaScript framework for building user interfaces"
  - name: Tailwind
    description: "Utility-first CSS framework for rapid UI development"
  - name: CloudFlare DNS and Proxy
    description: "Content delivery network and DDoS mitigation services"
  - name: Linode VPS
    description: "Scalable and reliable cloud hosting for deploying websites, applications, and databases."
  experience: "5+ years"
  availability: "Open to new projects"
  achievements: "Developed an abstract art wallpaper generator"
  contact:
    - title: github
      url: https://github.com/raystanza
    - title: x
      url: https://x.com/realcaptgeech
    - title: email
      url: mailto:raystanza@raystanza.uk

# Default Open Graph Settings
og:
  title: "An Exercise in Futility"
  description: "A personal blog and portfolio by Jim Sines."
  type: "website"
  image: "/assets/icons/og-image.png"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-github-metadata
  - jemoji
  - kramdown

collections_dir: all_collections
collections:
  posts:
    output: true
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
  - scope:
      path: "_projects"
    values:
      layout: "project"
      permalink: /projects/:title/


# Excluded items
exclude:
  - "sitemap.xml"
  - "feed.xml"
  - "LICENSE"
  - "README.md"
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/

github: [metadata]
