# Site settings
title: An exercise in futility
markdown: kramdown
email: raystanza@raystanza.uk
description: >- # ignore newlines until "baseurl:"
  This is a playground where an alternate 'Me' lives.
baseurl: "" # e.g. /docs
url: "https://raystanza.uk"
twitter_username: realcaptgeech
github_username: raystanza

author:
  name: Jim Sines
  email: raystanza@raystanza.uk
  dp: https://avatars.githubusercontent.com/u/51805268?v=4
  tagline: "<p>Coded by Jim Sines</p>"
  location: "USA"
  profession: "Wheelchair Repair Technician"
  languages: "English"
  education: "Self-taught"
  skills: "PHP, JavaScript, HTML, CSS"
  experience: "5+ years"
  availability: "Open to new projects"
  achievements: "Developed a portfolio of abstract art generators"
  contact:
    - title: github
      url: https://github.com/raystanza
    - title: x
      url: https://x.com/realcaptgeech
    - title: email
      url: mailto:raystanza@raystanza.uk

# Default Open Graph Settings
og:
  title: "An Exercise in Futility"
  description: "A personal blog and portfolio by Jim Sines."
  type: "website"
  image: "/assets/icons/og-image.png"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-github-metadata
  - jemoji
  - kramdown

collections_dir: all_collections
collections:
  posts:
    output: true
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
  - scope:
      path: "_projects"
    values:
      layout: "project"
      permalink: /projects/:title/


# Excluded items
exclude:
  - "sitemap.xml"
  - "feed.xml"
  - "LICENSE"
  - "README.md"
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/

github: [metadata]
